name: release-hash-check

on:
  pull_request:
    branches:
      - master
    paths:
      - .in-toto/*.link

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - id: files
      run: |
        echo "${{ github.sha }}"
        git --no-pager diff --name-only ${{ github.sha }}...master
        FILES=$(git --no-pager diff --name-only ${{ github.sha }}...master 2>/dev/null)
        echo "::set-output name=all::$FILES"

    - run: |
        python .github/workflows/release-hash-check.py ${{ steps.files.outputs.all }}